import { adminRoutesV1 } from '@/domains/admin/v1/routers';
import { authRoutesV1 } from '@/domains/auth/v1/routers';
import { chatRoutesV1 } from '@/domains/chat/v1/routers/chat.router';
import { discussionRoutesV1 } from '@/domains/chat/v1/routers/discussion.router';
import { courseRouterV1 } from '@/domains/course/v1/routers/';
import { enrollmentRouterV1 } from '@/domains/enrollment/v1/routers';
import { mediaRouterV1 } from '@/domains/media/v1/routers';
import { notificationRouterV1 } from '@/domains/notification/v1/routers';
import { orderRoutesV1 } from '@/domains/order/v1/routers';
import { paymentRoutesV1 } from '@/domains/payment/v1/routers';
import { userRouterV1 } from '@/domains/user/v1/routers';
import { instructorRouterV1 } from '@/domains/user/v1/routers/instructor.router';
import { authGuard } from '@/middlewares/auth.middleware';
import { blocklistMiddleware } from '@/middlewares/blocklist.middleware';
import { adminRateLimiter } from '@/services/security/ratelimiter';
import { Router } from 'express';
import { BaseRoutes } from './route.constants';

const router = Router();
router.use(BaseRoutes.users, userRouterV1);
router.use(BaseRoutes.instructors, instructorRouterV1);
router.use(BaseRoutes.auth, authRoutesV1);
router.use(BaseRoutes.media, authGuard(), mediaRouterV1);
router.use(BaseRoutes.courses, courseRouterV1);
router.use(BaseRoutes.chats, authGuard(), chatRoutesV1);
router.use(BaseRoutes.discussions, authGuard(), discussionRoutesV1);
router.use(BaseRoutes.orders, authGuard(), orderRoutesV1);
router.use(BaseRoutes.payments, authGuard(), paymentRoutesV1);
router.use(BaseRoutes.enrollments, authGuard(), enrollmentRouterV1);
router.use(BaseRoutes.notifications, authGuard(), notificationRouterV1);
router.use(BaseRoutes.admin, adminRoutesV1);

export { router as routerV1 };
